---
title: "Reflective Thinking Week 6"
author: "Haojie Liu"
date: "2023-05-11"
output: pdf_document
---

## Question 1

### Please share your initial thought/reaction (I’m going to ask a follow-up question) on the statement in this photograph.

I have no choice but follow after this statement. Also there is no I can stop say that the guy who worte this is so right. I've seen a lot of student who walk out of college with fancy grade but understand nothing about their career. The point of education, or in other word, us in college especially in UCLA, is to make each student to have the ability to provides more value to the society or family. Just a good grade does not means that you can have that kind of ability, however skills will. Including communicate with others, teamworks, ability to make things organized, be respect to others. A programming experts will not success out there without the skills I mentioned above. Therefore, as I looking into my own education, I will learning as much skills I can, and also keep the grades look good.


## Question 2

### There is a quote attributed to Aristotle:

### Learning is not child’s play; we cannot learn without pain.

### In response, my good friend said “If a student is consistently getting poor grades in their major or is experiencing excessive or chronic stress due to their academic difficulties – the student should change their major, learning should be a source of enjoyment – otherwise there is no learning”

### Consider your own experience, how have grades shaped your learning experience and do they have any relationto your skills?

Agree with both but I can't follow Aristotle.